FROM mysql:8.0

# load environment variables from .env file
ENV MYSQL_DATABASE=$MYSQL_DATABASE
ENV MYSQL_USER=$MYSQL_USER
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ENV MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

# copy setup script into the container
COPY setup.sql /docker-entrypoint-initdb.d/