FROM golang:1.21.1
ENV GOOS=linux GOARCH=arm64

#Setting the working dir in the container
WORKDIR /app



# Copy all .go files to the container
COPY *.go .

# Copy the go.mod and go.sum files to the container
COPY go.mod .
COPY go.sum .

RUN go mod download

# Install any required dependencies
RUN go get -d -v ./...

# Build the Go app
RUN go build -o raspiapp 

RUN chmod +x ./app

# Set the command to run the Go app
CMD ["/raspiapp"]