FROM postgres:15

# load environment variables from .env file
ENV POSTGRES_DB=$POSTGRES_DB
ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV POSTGRES_HOST=$POSTGRES_HOST
ENV POSTGRES_PORT=$POSTGRES_PORT
ENV POSTGRES_ROOT_PASSWORD=$POSTGRES_ROOT_PASSWORD

# copy setup script into the container
COPY setup.sql /docker-entrypoint-initdb.d/

# Expose the default PostgreSQL port
EXPOSE 5432