FROM arm64v8/debian:buster

#Setting the working dir in the container
WORKDIR /app

# Copy all .go files to the container
COPY *.go .

# Copy the go.mod and go.sum files to the container
COPY go.mod .
COPY go.sum .

RUN apt-get update && apt-get install -y 
RUN go mod download

# Install any required dependencies
RUN go get -d -v ./...

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o raspiapp 

# Set the command to run the Go app
CMD ["./raspiapp"]